apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-pod
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-pod
  template:
    metadata:
      labels:
        app: python-pod
    spec:
      containers:
      - name: python-pod
        image: ACCOUNTID.dkr.ecr.us-gov-west-1.amazonaws.com/kafka-custom:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"   # Minimum memory the container needs
            cpu: "1"       # Minimum CPU the container needs
          limits:
            memory: "1Gi"     # Maximum memory the container can use
            cpu: "2"          # Maximum CPU the container can use
